<?php

declare(strict_types=1);

namespace Nexia\Apps\Nexia\SubmissionProof\Http\Controllers;

use Nexia\Laravel\Access\Contracts\ResourceActionDecisions;
use Nexia\Laravel\Access\Contracts\ResourceAuthorization;
use Nexia\Laravel\ResourceTransfer\Concerns\BuildsResourceTransferMeta;
use Nexia\Laravel\Http\Concerns\ParsesResourceListQuery;
use Nexia\Laravel\Http\Controllers\Controller;
use Nexia\ResourceTransfer\Contracts\ResourceTransferDefinition;
use Nexia\ResourceTransfer\ResourceTransfers;
use Nexia\Apps\Nexia\SubmissionProof\Models\Note;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

/**
 * Note package-owned tenant API controller.
 *
 * Generated by `nexia-apps:make-package-resource`. Fill in app-specific
 * validation rules and serialization to match your domain. Route
 * middleware and the package-local policy both enforce the package
 * permission keys.
 *
 * List query handling is declarative via the `Filterable` model trait —
 * `Note` itself declares each list field once with its
 * search/filter/sort capabilities through `resourceListFields()`. The
 * frontend renders funnel chrome from
 * `meta.list_schema` and holds no allowlist mirror.
 */
class NoteController extends Controller
{
    use BuildsResourceTransferMeta;
    use ParsesResourceListQuery;

    // Authenticated App request; returns policy decisions only, never records.
    public function collectionActions(Request $request): JsonResponse
    {
        return response()->json(['meta' => ['actions' =>
            app(ResourceActionDecisions::class)->forCollection($request->user(), Note::class),
        ]]);
    }

    public function index(Request $request): JsonResponse
    {
        $listQuery = $this->resourceListQuery($request, new Note, default: 25, maximum: 100);

        $this->authorize('viewAny', Note::class);
        $query = Note::query()->visibleTo($request->user());

        $paginated = $query
            ->filters($listQuery)
            ->defaultSort('created_at', 'desc')
            ->paginate($listQuery->perPage);

        // Export/import affordances light up automatically once the model
        // opts in (`use ExportImportable;` + `transferColumns()`); this stays
        // null and harmless otherwise.
        $transfer = app(ResourceTransfers::class)->find('submission-proof.note');

        $actionDecisions = app(ResourceActionDecisions::class);

        return response()->json([
            'data' => collect($paginated->items())
                ->map(fn (Note $record): array => $this->serialize($request, $record, $actionDecisions))
                ->all(),
            'meta' => [
                'current_page' => $paginated->currentPage(),
                'last_page' => $paginated->lastPage(),
                'per_page' => $paginated->perPage(),
                'total' => $paginated->total(),
                'list_schema' => (new Note)->listSchema(),
                'actions' => $actionDecisions->forCollection($request->user(), Note::class),
                'resource_transfer' => $transfer instanceof ResourceTransferDefinition
                    ? $this->resourceTransferMeta($request, $transfer)
                    : null,
            ],
        ]);
    }

    public function show(Request $request, string $note): JsonResponse
    {
        $note = $this->resolveNote($note);

        $this->authorize('view', $note);

        return response()->json([
            'note' => $this->serialize(
                $request,
                $note,
                app(ResourceActionDecisions::class),
            ),
        ]);
    }

    public function store(Request $request): JsonResponse
    {
        $this->authorize('create', Note::class);

        $validated = $request->validate([
            'name' => ['required', 'string', 'max:255'],
        ]);

        $record = Note::create(array_merge(
            $validated,
            app(ResourceAuthorization::class)
                ->creationAttributes('submission-proof.note'),
        ));

        return response()->json([
            'note' => $this->serialize(
                $request,
                $record->refresh(),
                app(ResourceActionDecisions::class),
            ),
        ], 201);
    }

    public function update(Request $request, string $note): JsonResponse
    {
        $note = $this->resolveNote($note);

        $this->authorize('update', $note);

        $validated = $request->validate([
            'name' => ['sometimes', 'required', 'string', 'max:255'],
        ]);

        // Partial update: an omitted name intentionally leaves the record unchanged.
        $note->update($validated);

        return response()->json([
            'note' => $this->serialize(
                $request,
                $note->fresh(),
                app(ResourceActionDecisions::class),
            ),
        ]);
    }

    public function destroy(Request $request, string $note): JsonResponse
    {
        $note = $this->resolveNote($note);

        $this->authorize('delete', $note);

        // Keep history and allow recovery by public UUID through restore().
        // Tenant retirement owns final removal; this App has no purge action.
        $note->delete();

        return response()->json(['message' => __('submission-proof.note.deleted')]);
    }

    public function restore(Request $request, string $note): JsonResponse
    {
        $record = Note::onlyTrashed()->where('public_id', $note)->firstOrFail();
        $this->authorize('restore', $record);
        $record->restore();

        return response()->json(['note' => $this->serialize(
            $request, $record->refresh(), app(ResourceActionDecisions::class),
        )]);
    }

    private function resolveNote(string $note): Note
    {
        return Note::query()->where('public_id', $note)->firstOrFail();
    }

    /** @return array<string, mixed> */
    private function serialize(
        Request $request,
        Note $record,
        ResourceActionDecisions $actionDecisions,
    ): array {
        return [
            ...$record->toArray(),
            'actions' => $actionDecisions->forRecord($request->user(), $record),
        ];
    }
}
