<?php

declare(strict_types=1);

namespace Nexia\Apps\Nexia\SubmissionProof\Models;

use Nexia\Laravel\Access\Contracts\ResourceAuthorization;
use Nexia\Laravel\Models\Concerns\Filterable;
use Nexia\Laravel\Models\Concerns\HasDisplayLabel;
use Nexia\Laravel\Models\Concerns\HasPublicUuid;
use Nexia\Laravel\Models\NexiaEntityModel;
use Nexia\Laravel\Resources\ResourceListFields;
use Nexia\Identity\Contracts\Actor;
use Illuminate\Database\Eloquent\Builder;

/**
 * Note — package-owned tenant API resource.
 *
 * Generated by `nexia-apps:make-package-resource`. Extend this model with the
 * fields, casts, scopes, and relations your app domain requires. It follows
 * the same tenant collection-resource baseline as `nexia-resources:make-resource`,
 * while remaining inside the package boundary.
 */
class Note extends NexiaEntityModel
{
    use Filterable;
    use HasDisplayLabel;
    use HasPublicUuid;

    protected $table = 'submission_proof_notes';

    // Public responses use UUIDs; database keys stay inside the App.
    protected $hidden = ['id', 'legal_entity_id'];

    protected $fillable = [
        'public_id',

        'name',
    ];

    // ── Filterable list catalog ─────────────────────────────────────

    public function resourceListFields(): ResourceListFields
    {
        return ResourceListFields::make()
            ->field('created_at', sortable: true)
            ->field('name', searchable: true, sortable: true);
    }

    // ── Export / import (opt-in) ────────────────────────────────────
    //
    // The generated controller and list surface already forward
    // `meta.resource_transfer`, so the shell export/import button appears
    // automatically once this model opts in. To enable it: add
    // `use Nexia\Laravel\ResourceTransfer\Concerns\ExportImportable;` to the imports,
    // add `use ExportImportable;` to the trait list above, then declare the
    // transfer columns (prefer i18n-key labels like `resourceListFields()`):
    //
    // public static function transferColumns(\Nexia\ResourceTransfer\TransferSchema $schema): \Nexia\ResourceTransfer\TransferSchema
    // {
    //     return $schema
    //         ->key('public_id', 'submission-proof.note.id.label') // unique import key
    //         ->field('name', 'submission-proof.note.name.label', required: true);
    // }
    //
    // Reuse scopeVisibleTo for export so the declared record ownership applies
    // to list and export rows identically. Operating Unit-owned resources must
    // additionally opt into TRANSFER_SCOPE_ORGANIZATION; tenant-owned resources
    // retain the tenant-wide transfer scope:
    //
    // public static function transferScope(): string
    // {
    //     return self::TRANSFER_SCOPE_ORGANIZATION;
    // }
    //
    // public static function transferExportQuery(?\Illuminate\Contracts\Auth\Authenticatable $actor = null): Builder
    // {
    //     return $actor instanceof Actor ? static::query()->visibleTo($actor) : static::query()->whereRaw('1 = 0');
    // }

    public function scopeVisibleTo(Builder $query, Actor $user): Builder
    {
        return app(ResourceAuthorization::class)
            ->scopeVisible($query, 'submission-proof.note');
    }

    /**
     * Canonical human-readable label surfaced as `display_label` in
     * every JSON response. Use the generated name field, with the UUID
     * as a fallback for records whose name has not been supplied.
     */
    public function displayLabel(): string
    {
        return trim((string) $this->name) !== '' ? (string) $this->name : (string) $this->public_id;
    }
}
